In [2]:
print("all ok")

all ok


In [3]:
import pandas as pd

In [4]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})

In [5]:
data

,text,output
0,people watch cricket,1
1,cricket watch cricket,1
2,people give comment,0
3,cricket give comment,0


In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
BOW=CountVectorizer()

In [8]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [9]:
document_matrix=BOW.fit_transform(data["text"])

In [10]:
document_matrix.toarray()

array([[0, 1, 0, 1, 1],
       [0, 2, 0, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 1, 1, 0, 0]])

In [11]:
document_matrix[1].toarray()

array([[0, 2, 0, 0, 1]])

vocabulary                         {'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}<br>
alphabetical vocabulary            [comment, cricket, give, people, watch]<br>
d2                                 cricket watch cricket<br>
d2 vector representation           [0,2,0,0,1]<br>
document_matrix[1].toarray()       array([[0, 2, 0, 0, 1]])<br>
Conclusion                         Both are same as per conceptual and practical understanding of BOW

#### Alphabetical sequence- based on the sequence/index

In [12]:
BOW.vocabulary_

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

#### Implement OHE for the below data using ANY library(for example numpy, pandas, tf, pytorch)

#### after completing this tag me and krish sir and send your solution in group chat

#### in next class i will give you the quick overview of it

### Bigram, Trigram Concept

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
bigram=CountVectorizer(ngram_range=(2,2))

In [15]:
trigram=CountVectorizer(ngram_range=(3,3))

In [16]:
bigram_matrix=bigram.fit_transform(data["text"])

In [17]:
bigram.vocabulary_

{'people watch': 4,
 'watch cricket': 5,
 'cricket watch': 1,
 'people give': 3,
 'give comment': 2,
 'cricket give': 0}

In [18]:
trigram_matrix=trigram.fit_transform(data["text"])

In [19]:
trigram.vocabulary_

{'people watch cricket': 3,
 'cricket watch cricket': 1,
 'people give comment': 2,
 'cricket give comment': 0}

In [20]:
uni_bigram=CountVectorizer(ngram_range=(1,2))

In [21]:
uni_bigram_matrix=uni_bigram.fit_transform(data["text"])

In [22]:
uni_bigram.vocabulary_

{'people': 6,
 'watch': 9,
 'cricket': 1,
 'people watch': 8,
 'watch cricket': 10,
 'cricket watch': 3,
 'give': 4,
 'comment': 0,
 'people give': 7,
 'give comment': 5,
 'cricket give': 2}

In [23]:
mix=CountVectorizer(ngram_range=(1,3))

In [24]:
mix_matrix=mix.fit_transform(data["text"])

In [25]:
mix.vocabulary_

{'people': 8,
 'watch': 13,
 'cricket': 1,
 'people watch': 11,
 'watch cricket': 14,
 'people watch cricket': 12,
 'cricket watch': 4,
 'cricket watch cricket': 5,
 'give': 6,
 'comment': 0,
 'people give': 9,
 'give comment': 7,
 'people give comment': 10,
 'cricket give': 2,
 'cricket give comment': 3}

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [28]:
tfidf=TfidfVectorizer()

In [29]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.49681612, 0.        , 0.61366674, 0.61366674],
       [0.        , 0.8508161 , 0.        , 0.        , 0.52546357],
       [0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.61366674, 0.49681612, 0.61366674, 0.        , 0.        ]])

#### Vocabulary

In [ ]:
feature_names = tfidf.get_feature_names_out()

print("Feature Names:", feature_names)

Feature Names: ['comment' 'cricket' 'give' 'people' 'watch']


#### idf vector

idf values for ['comment' 'cricket' 'give' 'people' 'watch']

In [31]:
tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])