In [1]:
print("all ok")

all ok


In [2]:
sentences = ["I ate dinner.", 
       "We had a three-course meal.", 
       "Brad came to dinner with us.",
       "He loves fish tacos.",
       "In the end, we all felt like we ate too much.",
       "We all agreed; it was a magnificent evening."]

### Sentence Embedding Techniques

1. sentence transformer
2. langchain huggingface
3. transformer

### Sentence Transformer

In [7]:
from sentence_transformers import SentenceTransformer

c:\Users\rkama\OneDrive\Full-Stack-GenAI-Bootcamp-Theory\Advance-NLP-GenerativeAI-Bootcamp-VSCode\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
model=SentenceTransformer("all-mpnet-base-v2")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3415.28it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [9]:
sentences[0]

'I ate dinner.'

In [ ]:
# vector representation of the sentence "I ate dinner"
model.encode(sentences[0])

array([-1.58598628e-02,  4.59825397e-02, -1.46349799e-02, -4.85908352e-02,
       -3.60325165e-03,  3.17664258e-02, -3.27771902e-02,  2.11894736e-02,
        1.07366936e-02,  2.50182655e-02,  1.58237461e-02,  1.24069834e-02,
        1.62090044e-02, -1.30434483e-02,  4.58447039e-02,  4.40269634e-02,
        4.57802266e-02, -4.32262756e-03,  1.87806934e-02,  5.22197830e-03,
       -1.86415520e-02, -7.11810449e-03,  3.01358849e-02,  1.70696024e-02,
       -1.53763909e-02,  3.34172025e-02, -6.55886857e-03,  1.58591475e-02,
        1.37039712e-02, -2.02766676e-02,  3.26632671e-02,  5.48362266e-03,
       -3.53351310e-02, -1.06665172e-01,  1.85711554e-06,  3.66638862e-02,
       -1.71335395e-02,  3.34468186e-02, -6.43021688e-02,  6.90796226e-02,
        2.50845514e-02,  2.89431233e-02, -8.98414291e-03, -1.84546299e-02,
        2.81152315e-02, -2.34797690e-02,  1.21612493e-02,  6.25150651e-02,
       -8.58703777e-02, -1.84621545e-03,  7.95865897e-03, -8.42522532e-02,
       -2.26103980e-02,  

In [11]:
model.encode(sentences[0]).shape

(768,)

### Langchain Hugginface

In [21]:
from langchain_huggingface import HuggingFaceEmbeddings

In [22]:
embedding_model_name = "sentence-transformers/all-mpnet-base-v2"

In [23]:
model_kwargs = {"device": "cpu"}
embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name, model_kwargs=model_kwargs)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3348.27it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [25]:
sentences[0]

'I ate dinner.'

In [27]:
embedding_vector = embeddings.embed_query(sentences[0])

In [29]:
embedding_vector

[-0.01585986278951168,
 0.045982539653778076,
 -0.014634979888796806,
 -0.04859083518385887,
 -0.003603251650929451,
 0.03176642581820488,
 -0.03277719020843506,
 0.021189473569393158,
 0.010736693628132343,
 0.02501826547086239,
 0.015823746100068092,
 0.01240698341280222,
 0.016209004446864128,
 -0.013043448328971863,
 0.045844703912734985,
 0.04402696341276169,
 0.04578022658824921,
 -0.004322627559304237,
 0.018780693411827087,
 0.005221978295594454,
 -0.018641551956534386,
 -0.007118104491382837,
 0.030135884881019592,
 0.017069602385163307,
 -0.015376390889286995,
 0.03341720253229141,
 -0.006558868568390608,
 0.015859147533774376,
 0.013703971169888973,
 -0.020276667550206184,
 0.032663267105817795,
 0.005483622662723064,
 -0.035335130989551544,
 -0.10666517168283463,
 1.8571155351310153e-06,
 0.03666388615965843,
 -0.01713353954255581,
 0.033446818590164185,
 -0.06430216878652573,
 0.06907962262630463,
 0.02508455142378807,
 0.028943123295903206,
 -0.008984142914414406,
 -0.018

In [30]:
len(embedding_vector)

768

### One more approach with Transformer Huggingface Library

In [31]:
import torch
from transformers import BertTokenizer, BertModel
import random

In [32]:
tokenizer=BertTokenizer.from_pretrained('bert-base-uncased')

c:\Users\rkama\OneDrive\Full-Stack-GenAI-Bootcamp-Theory\Advance-NLP-GenerativeAI-Bootcamp-VSCode\venv\lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\rkama\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [33]:
model=BertModel.from_pretrained('bert-base-uncased')

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3771.60it/s]
BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [39]:
text = "follow sunny for genai learning"

In [40]:
encoding = tokenizer([text],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [43]:
# input_ids are the token ids for each word in the sentence "follow sunny for genai learning"
input_ids=encoding["input_ids"]
input_ids

tensor([[  101,  3582, 11559,  2005,  8991,  4886,  4083,   102]])

In [44]:
# attention mask is telling each and every word is required from sentence "follow sunny for genai learning" for creating embedding vector
attention_mask=encoding["attention_mask"]
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
# code to generate word based embedding vector for the sentence "follow sunny for genai learning"

with torch.no_grad():
    outputs=model(input_ids=input_ids, attention_mask=attention_mask)
    word_embeddings=outputs.last_hidden_state

In [46]:
word_embeddings

tensor([[[-0.0046, -0.1060, -0.0177,  ...,  0.0474,  0.0697,  0.2605],
         [ 0.8739, -0.1599,  0.5948,  ...,  0.4223,  0.2269, -0.1508],
         [ 0.0209, -0.3746, -0.2735,  ...,  0.3497,  0.0062, -0.4563],
         ...,
         [-0.2692, -0.4198, -0.1005,  ..., -0.0563, -0.2520, -0.6442],
         [-0.4552, -0.7338, -0.2614,  ...,  0.8366,  0.2496, -0.1972],
         [ 0.8920,  0.1769, -0.2345,  ...,  0.3265, -0.7962, -0.2090]]])

In [47]:
word_embeddings.shape

torch.Size([1, 8, 768])

In [48]:
# Lets decode word embedding vector to word token using tokenizer

decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [49]:
decode

'follow sunny for genai learning'

### These above entire techniques based on the transformer model

### Which we gonna use in further classes for RAG finetuning etc

https://huggingface.co/BAAI

https://huggingface.co/sentence-transformers

https://www.sbert.net/

https://huggingface.co/models?library=sentence-transformers&sort=downloads

https://huggingface.co/spaces/mteb/leaderboard

https://huggingface.co/blog/mteb